using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AndroidEmulatorPlus.Services;

public sealed class HandoffDescriptor
{
    [JsonPropertyName("tool")] public string Tool { get; init; } = "generic";
    [JsonPropertyName("serial")] public string Serial { get; init; } = "";
    [JsonPropertyName("transport")] public string Transport { get; init; } = "";
    [JsonPropertyName("apiLevel")] public string? ApiLevel { get; init; }
    [JsonPropertyName("model")] public string? Model { get; init; }
    [JsonPropertyName("packages")] public List<string> Packages { get; init; } = [];
    [JsonPropertyName("sdkRoot")] public string? SdkRoot { get; init; }
    [JsonPropertyName("adbPath")] public string? AdbPath { get; init; }
    [JsonPropertyName("exportedUtc")] public string ExportedUtc { get; init; } = "";
    [JsonPropertyName("sampleCommands")] public Dictionary<string, string> SampleCommands { get; init; } = new();
}

public sealed class HandoffExportService
{
    private readonly AdbService _adb;
    private readonly SdkLocator _sdk;
    private readonly LogService _log;

    public HandoffExportService(AdbService adb, SdkLocator sdk, LogService log)
    {
        _adb = adb;
        _sdk = sdk;
        _log = log;
    }

    public async Task<HandoffDescriptor> BuildDescriptorAsync(string serial, CancellationToken ct = default)
    {
        var device = (await _adb.ListDevicesAsync(ct)).FirstOrDefault(d => d.Serial == serial);
        var transport = device is not null ? AdbService.InferTransport(device) : "unknown";

        string? apiLevel = null;
        try
        {
            var props = await _adb.ShellAsync(serial, "getprop ro.build.version.sdk", ct);
            apiLevel = props.StdOut.Trim();
        }
        catch { }

        var packages = await _adb.ListPackagesAsync(serial, ct: ct);

        var sampleCommands = new Dictionary<string, string>
        {
            ["appium_caps"] = $@"{{""platformName"":""Android"",""appium:automationName"":""UiAutomator2"",""appium:udid"":""{serial}""}}",
            ["maestro_launch"] = $"maestro --device {serial} test flow.yaml",
            ["adb_shell"] = $"adb -s {serial} shell",
        };

        return new HandoffDescriptor
        {
            Tool = "generic",
            Serial = serial,
            Transport = transport,
            ApiLevel = apiLevel,
            Model = device?.Model,
            Packages = packages,
            SdkRoot = _sdk.SdkRoot,
            AdbPath = _sdk.AdbExe,
            ExportedUtc = DateTime.UtcNow.ToString("O"),
            SampleCommands = sampleCommands,
        };
    }

    public string ExportJson(HandoffDescriptor descriptor, string destPath)
    {
        var json = JsonSerializer.Serialize(descriptor, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(destPath, json);
        _log.Success($"Handoff exported: {destPath}");
        return destPath;
    }

    public string ExportMaestroYaml(HandoffDescriptor descriptor, string destPath)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Maestro flow generated by AndroidEmulatorPlus");
        sb.AppendLine($"# Device: {descriptor.Serial} ({descriptor.Transport})");
        sb.AppendLine($"# API: {descriptor.ApiLevel ?? "unknown"}");
        sb.AppendLine($"# Exported: {descriptor.ExportedUtc}");
        sb.AppendLine();
        sb.AppendLine("appId: com.example.app");
        sb.AppendLine("---");
        sb.AppendLine("- launchApp");
        sb.AppendLine("- assertVisible: \".*\"");
        File.WriteAllText(destPath, sb.ToString());
        _log.Success($"Maestro template: {destPath}");
        return destPath;
    }
}
